name: sklearndev
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py_0
  - appnope=0.1.0=py37_1000
  - asn1crypto=0.24.0=py37_1003
  - atomicwrites=1.3.0=py_0
  - attrs=19.1.0=py_0
  - babel=2.7.0=py_0
  - backcall=0.1.0=py_0
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_0
  - cffi=1.12.3=py37hccf1714_0
  - chardet=3.0.4=py37_1003
  - cryptography=2.7=py37h212c5bf_0
  - cycler=0.10.0=py_1
  - cython=0.29.10=py37h6de7cb9_0
  - decorator=4.4.0=py_0
  - docutils=0.14=py37_1001
  - freetype=2.10.0=h24853df_0
  - idna=2.8=py37_1000
  - imagesize=1.1.0=py_0
  - importlib_metadata=0.18=py37_0
  - ipykernel=5.1.1=py37h24bf2e0_0
  - ipython=7.5.0=py37h24bf2e0_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.14.0=py37_0
  - jinja2=2.10.1=py_0
  - joblib=0.13.2=py_0
  - jupyter_client=5.2.4=py_3
  - jupyter_core=4.4.0=py_0
  - kiwisolver=1.1.0=py37h770b8ee_0
  - libblas=3.8.0=7_openblas
  - libcblas=3.8.0=7_openblas
  - libcxx=8.0.0=2
  - libcxxabi=8.0.0=2
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=3.0.1=0
  - liblapack=3.8.0=7_openblas
  - libpng=1.6.37=h2573ce8_0
  - libsodium=1.0.16=h1de35cc_1001
  - llvm-openmp=8.0.0=h770b8ee_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - matplotlib=3.1.0=py37_1
  - matplotlib-base=3.1.0=py37h3a684a6_1
  - more-itertools=4.3.0=py37_1000
  - ncurses=6.1=h0a44026_1002
  - numpy=1.16.4=py37h6b0580a_0
  - openblas=0.3.5=h436c29b_1001
  - openssl=1.1.1b=h01d97ff_2
  - packaging=19.0=py_0
  - parso=0.5.0=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.1.1=py37_0
  - pluggy=0.12.0=py_0
  - prompt_toolkit=2.0.9=py_0
  - ptyprocess=0.6.0=py_1001
  - py=1.8.0=py_0
  - pycparser=2.19=py37_1
  - pygments=2.4.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pysocks=1.7.0=py37_0
  - pytest=4.6.3=py37_0
  - python=3.7.3=h0d93f26_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - pyzmq=18.0.1=py37h2d07e9b_1
  - readline=7.0=hcfe32e1_1001
  - requests=2.22.0=py37_0
  - scikit-learn=0.21.2=py37h2a6a0b8_0
  - scipy=1.3.0=py37hab3da7d_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_1000
  - snowballstemmer=1.2.1=py_1
  - sphinx=2.1.2=py_0
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.1=py_0
  - sqlite=3.28.0=h9721f7c_0
  - tk=8.6.9=h2573ce8_1002
  - tornado=6.0.2=py37h01d97ff_0
  - traitlets=4.3.2=py37_1000
  - urllib3=1.24.3=py37_0
  - wcwidth=0.1.7=py_1
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h1de35cc_1001
  - zeromq=4.3.1=h0a44026_1000
  - zipp=0.5.1=py_0
  - zlib=1.2.11=h1de35cc_1004
prefix: /Users/4bic/anaconda3/envs/sklearndev

