channels:
  - conda-forge
dependencies:
  - numpy
  - blas[build=mkl]
  - scipy
  - cython
  - joblib
  - threadpoolctl
  - pandas
  - matplotlib
  - pyamg
  - pillow
  - pytest=6.2.5
  - pytest-xdist
  - codecov
  - pytest-cov
  - coverage=6.2
  - ccache
