
name: Assign
on:
  issue_comment:
    types: created

jobs:
  one:
    runs-on: ubuntu-latest
    # Support common whitespace patterns after take. Note that string
    # comparisons is not case sensitive.
    # toJson(github.event.comment.body) allows newline to be detected
    if: >-
      (github.event.comment.body == 'take' ||
       github.event.comment.body == 'take ' ||
       toJson(github.event.comment.body) == 'take\r\n' )
      && !github.event.issue.assignee
    steps:
      - run: |
          echo "Assigning issue ${{ github.event.issue.number }} to ${{ github.event.comment.user.login }}"
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d '{"assignees": ["${{ github.event.comment.user.login }}"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X "DELETE" https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels/help%20wanted
