name: Check Changelog

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'no-changelog') == 0 }}
    steps:
      - name: Get PR number and author
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_AUTHOR=${{ github.event.pull_request.user.login }}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Check the changelog
        run: |
          set -xe
          result=`grep "$PR_NUMBER" ./doc/whats_new/v*.rst | grep "$PR_AUTHOR"`
          if [ "$result" != "" ]
          then
            echo $result
          else
          then
            echo "Changelog entry is missing."
            exit 1
          fi
