name: Check Milestone (when failing needs Triage intervention)
# This check makes sure that the milestone is properly set.
# To bypass this check, label the PR with "Long Term".
on:
  pull_request:
    types: [opened, edited, labeled, unlabeled, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Long Term') == 0 }}
    steps:
      - name: Check the milestone
        run: |
          set -xe
          if [ ${{ github.event.pull_request.milestone.title }} == "" ]
          then
              echo "No milestone has been set."
              exit 1
          fi

